export { default as SunIcon } from './sun.svg';
export { default as MoonIcon } from './moon.svg';
export { default as MercuryIcon } from './mercury.svg';
export { default as VenusIcon } from './venus.svg';
export { default as MarsIcon } from './mars.svg';
export { default as JupiterIcon } from './jupiter.svg';
export { default as SaturnIcon } from './saturn.svg';
export { default as UranusIcon } from './uranus.svg';
export { default as NeptuneIcon } from './neptune.svg';
export { default as PlutoIcon } from './pluto.svg';

export { default as AriesIcon } from './aries.svg'
export { default as TaurusIcon } from './taurus.svg'
export { default as GeminiIcon } from './gemini.svg'
export { default as CancerIcon } from './cancer.svg'
export { default as LeoIcon } from './leo.svg'
export { default as VirgoIcon } from './virgo.svg'
export { default as LibraIcon } from './libra.svg'
export { default as ScorpioIcon } from './scorpio.svg'
export { default as SagittariusIcon } from './sagittarius.svg'
export { default as CapricornIcon } from './capricorn.svg'
export { default as AquariusIcon } from './aquarius.svg'
export { default as PiscesIcon } from './pisces.svg'

export { default as RelationsIcon } from './relations.svg'
export { default as FinanceIcon } from './finance.svg'
export { default as CareerIcon } from './career.svg'
export { default as PersonIcon } from './person.svg'
export { default as LifeIcon } from './life.svg'
export { default as PartnerIcon } from './partner.svg'
export { default as HouseIcon } from './house.svg'